/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cefet.lp2.BDApplicationTeste.view.servico;

import br.cefet.lp2.BDApplicationTeste.dao.DaoException;
import br.cefet.lp2.BDApplicationTeste.dao.ServicoDao;
import br.cefet.lp2.BDApplicationTeste.entidade.Servico;
import javax.swing.JOptionPane;

/**
 *
 * @author douglas
 */
public class ServicoInserir extends javax.swing.JDialog {

    private Servico Servico = null;
    
    public Servico getServico(){
        return Servico;
    }
    
    /**
     * Creates new form ServicoInserirJDialog
     */
    public ServicoInserir(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Inserção de Serviços");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bCancelar = new javax.swing.JButton();
        bInserir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tDescricao = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tValor = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserção de Pet");
        setMaximumSize(new java.awt.Dimension(364, 230));
        setMinimumSize(new java.awt.Dimension(364, 230));
        setPreferredSize(new java.awt.Dimension(364, 230));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 5));

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(bCancelar);

        bInserir.setText("Inserir");
        bInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInserirActionPerformed(evt);
            }
        });
        jPanel1.add(bInserir);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 8));

        jPanel3.setPreferredSize(new java.awt.Dimension(315, 25));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Descrição :");
        jLabel1.setPreferredSize(new java.awt.Dimension(75, 16));
        jPanel3.add(jLabel1);

        tDescricao.setColumns(15);
        jPanel3.add(tDescricao);

        jPanel2.add(jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(315, 25));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Valor : ");
        jLabel2.setPreferredSize(new java.awt.Dimension(75, 16));
        jPanel4.add(jLabel2);

        tValor.setColumns(15);
        jPanel4.add(tValor);

        jPanel2.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(315, 25));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
        jPanel2.add(jPanel5);

        jPanel6.setPreferredSize(new java.awt.Dimension(315, 25));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
        jPanel2.add(jPanel6);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInserirActionPerformed
        try {
        Servico p = new Servico();
        p.setDescricao(tDescricao.getText());
        p.setValor(Double.parseDouble(tValor.getText()));
        
        ServicoDao dao = new ServicoDao ();
        int codServico = dao.inserir(p);
        p.setCod(codServico);
        this.Servico = p;
        JOptionPane.showMessageDialog(this, "Servico inserido com sucesso.");
        this.setVisible(false);
        this.dispose();
        }catch (DaoException ex){
            
        }
    }//GEN-LAST:event_bInserirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bInserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField tDescricao;
    private javax.swing.JTextField tValor;
    // End of variables declaration//GEN-END:variables
}
