/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cefet.lp2.BDApplicationTeste.view.servico;

import br.cefet.lp2.BDApplicationTeste.dao.DaoException;
import br.cefet.lp2.BDApplicationTeste.dao.ServicoDao;
import br.cefet.lp2.BDApplicationTeste.entidade.Servico;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author douglas
 */
public class ServicoCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TesteJFrame
     */
    public ServicoCadastro() {
        initComponents();

        ServicoDao dao = new ServicoDao();

        List<Servico> pList = new LinkedList<>();

        try {
            ServicoDao.lista = (ArrayList<Servico>) dao.consultarTodos();

        } catch (DaoException e) {
            JOptionPane.showMessageDialog(this, "Erro ao consultar todos os Servicos: " + e.getMessage());
        }

        preencherJTable(ServicoDao.lista);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        bInserir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaServicos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        bAlterar = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 350));

        jPanel1.setLayout(new java.awt.BorderLayout());

        bInserir.setText("+");
        bInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInserirActionPerformed(evt);
            }
        });
        jPanel3.add(bInserir);

        jPanel1.add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Nome:");
        jPanel4.add(jLabel1);

        tFiltro.setColumns(20);
        tFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tFiltroKeyPressed(evt);
            }
        });
        jPanel4.add(tFiltro);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tabelaServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaServicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaServicos);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        bAlterar.setText("Alterar");
        bAlterar.setEnabled(false);
        bAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(bAlterar);

        bExcluir.setText("Excluir");
        bExcluir.setEnabled(false);
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(bExcluir);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInserirActionPerformed
        ServicoInserir pInsertJDialog = new ServicoInserir(this, true);
        pInsertJDialog.setVisible(true);
        
        Servico p = pInsertJDialog.getServico();
        if (p != null){
            
            ServicoDao.lista.add(p);
            preencherJTable(ServicoDao.lista);
        }
        
    }//GEN-LAST:event_bInserirActionPerformed

    private void tFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFiltroKeyPressed
        if (evt.getKeyCode() == 10) {
            try {
                List<Servico> pList = new LinkedList<>();
                
                ServicoDao dao = new ServicoDao();
                pList = dao.consultarPorDescricao(tFiltro.getText());
                
                preencherJTable(pList);
            } catch (DaoException ex) {
                Logger.getLogger(ServicoCadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tFiltroKeyPressed

    private void tabelaServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaServicosMouseClicked
        bAlterar.setEnabled(true);
        bExcluir.setEnabled(true);
    }//GEN-LAST:event_tabelaServicosMouseClicked

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
        int linha = tabelaServicos.getSelectedRow();
        DefaultTableModel tModel = (DefaultTableModel) tabelaServicos.getModel();
        int cod = getCodServicoFromTable();
        
        int opt = JOptionPane.showConfirmDialog(this, "Confirma a exclusão do Servico de código " + cod + "?");
        if (opt == JOptionPane.OK_OPTION){
            try{
                ServicoDao dao = new ServicoDao();
                dao.excluir(cod);
                
                tModel.removeRow(linha);
                
                bAlterar.setEnabled(false);
                bExcluir.setEnabled(false);
            } catch(Exception e){
                JOptionPane.showMessageDialog(this, "Erro ao excluir Servico :- " +e.getMessage(), "Erro de Excluão", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_bExcluirActionPerformed

    private void bAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlterarActionPerformed
        int linha = tabelaServicos.getSelectedRow();
        DefaultTableModel tModel = (DefaultTableModel) tabelaServicos.getModel();
        int cod = getCodServicoFromTable();
        
        ServicoAlterar dialog = new ServicoAlterar(this, true, cod);
        dialog.setVisible(true);
        
        Servico p = dialog.getServico();
        if (p != null){
            tModel.setValueAt(p.getCod()+"", linha, 0);
            tModel.setValueAt(p.getDescricao(), linha, 1);
            tModel.setValueAt(p.getValor(), linha, 2);
            
        }
        
        
    }//GEN-LAST:event_bAlterarActionPerformed

    public int getCodServicoFromTable(){
        int linha = tabelaServicos.getSelectedRow();
        
        DefaultTableModel tModel = (DefaultTableModel) tabelaServicos.getModel();
        
        String codStr = tModel.getValueAt(linha, 0).toString();
        int cod = Integer.parseInt(codStr);
        
        return  cod;
    }
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlterar;
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bInserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tFiltro;
    private javax.swing.JTable tabelaServicos;
    // End of variables declaration//GEN-END:variables

    private void preencherJTable(List<Servico> pList) {
        String[] colunas = new String[]{"Cod.", "Descrição", "Valor"};

        String[][] dados = new String[pList.size()][5];
        for (int i = 0; i < pList.size(); i++) {
            Servico p = pList.get(i);
            dados[i][0] = p.getCod() + "";
            dados[i][1] = p.getDescricao();
            dados[i][2] = p.getValor()+"";
        }

        tabelaServicos.setModel(new javax.swing.table.DefaultTableModel(
                dados, colunas
        ));
        
        bAlterar.setEnabled(false);
        bExcluir.setEnabled(false);
    }
}
