/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cefet.lp2.BDApplicationTeste.view.pet;

import br.cefet.lp2.BDApplicationTeste.dao.DaoException;
import br.cefet.lp2.BDApplicationTeste.dao.PetDao;
import br.cefet.lp2.BDApplicationTeste.entidade.Pet;
import br.cefet.lp2.BDApplicationTeste.util.DateParse;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author douglas
 */
public class PetCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TesteJFrame
     */
    public PetCadastro() {
        initComponents();

        PetDao dao = new PetDao();

        List<Pet> pList = new LinkedList<>();

        try {
            pList = dao.consultarTodos();

        } catch (DaoException e) {
            JOptionPane.showMessageDialog(this, "Erro ao consultar todos os pets: " + e.getMessage());
        }

        preencherJTable(pList);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 350));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jPanel1.add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Nome:");
        jPanel4.add(jLabel1);

        jTextField1.setColumns(20);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel4.add(jTextField1);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton2.setText("Alterar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("Excluir");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PetInserir pInsertJDialog = new PetInserir(this, true);
        pInsertJDialog.setVisible(true);
        
        Pet p = pInsertJDialog.getPet();
        if (p != null){
            List<Pet> pList = new ArrayList<Pet>();
            pList.add(p);
            
            preencherJTable(pList);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == 10) {
            List<Pet> pList = new LinkedList<>();

            try {
                PetDao dao = new PetDao();
                pList = dao.consultarPorNome(jTextField1.getText());

            } catch (DaoException e) {
                JOptionPane.showMessageDialog(this, "Erro ao consultar todos os pets: " + e.getMessage());
            }
            
            preencherJTable(pList);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int linha = jTable1.getSelectedRow();
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        int cod = getCodPetFromTable();
        
        int opt = JOptionPane.showConfirmDialog(this, "Confirma a exclusão do Pet de código " + cod + "?");
        if (opt == JOptionPane.OK_OPTION){
            try{
                PetDao dao = new PetDao();
                dao.excluir(cod);
                
                tModel.removeRow(linha);
                
                jButton2.setEnabled(false);
                jButton3.setEnabled(false);
            } catch(Exception e){
                JOptionPane.showMessageDialog(this, "Erro ao excluir pet :- " +e.getMessage(), "Erro de Excluão", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int linha = jTable1.getSelectedRow();
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        int cod = getCodPetFromTable();
        
        PetAlterar dialog = new PetAlterar(this, true, cod);
        dialog.setVisible(true);
        
        Pet p = dialog.getPet();
        if (p != null){
            tModel.setValueAt(p.getCod()+"", linha, 0);
            tModel.setValueAt(p.getNome(), linha, 1);
            tModel.setValueAt(p.getDono(), linha, 2);
            tModel.setValueAt(p.getRaca(), linha, 3);
            tModel.setValueAt( DateParse.dateToString( p.getDtNasc() ), linha, 4);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public int getCodPetFromTable(){
        int linha = jTable1.getSelectedRow();
        
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        
        String codStr = tModel.getValueAt(linha, 0).toString();
        int cod = Integer.parseInt(codStr);
        
        return  cod;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void preencherJTable(List<Pet> pList) {
        String[] colunas = new String[]{"Cod.", "Nome", "Dono", "Raça", "Dt. Nasc."};

        String[][] dados = new String[pList.size()][5];
        for (int i = 0; i < pList.size(); i++) {
            Pet p = pList.get(i);
            dados[i][0] = p.getCod() + "";
            dados[i][1] = p.getNome();
            dados[i][2] = p.getDono();
            dados[i][3] = p.getRaca();
            dados[i][4] = DateParse.dateToString(p.getDtNasc(), "dd/MM/yyyy");
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                dados, colunas
        ));
        
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
    }
}
